### ISSUE TITLE
Typo on zshrc and bashrc

### ISSUE THREAD

**Issue by boratanrikulu** [PauSiber/update#1]
There is an typo on zshrc and bashrc files. **`opn`** should rename as **`xdg-open`**.

**Comment by boratanrikulu** [comment]
A source: https://www.cyberciti.biz/faq/how-to-use-sed-to-find-and-replace-text-in-files-in-linux-unix-shell/

**Comment by boratanrikulu** [comment]
You should pay attention to file ownership and permissions.

**Comment by murattanriverdi** [comment]
Theres is another solution too. We can simply define an alias.

```sh
echo "alias open='xdg-open' "  >> /home/dev/.zshrc
```

Source: https://askubuntu.com/questions/808053/alias-xdg-open-to-open

**Comment by boratanrikulu** [comment]
https://github.com/PauSiber/update/pull/3/commits/e08650ad5fd57fb757c054a2d6aed6185351550a#diff-363e43d57f11a6901f4b2781d67cca06
